server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/raduAndrada/microsevices-config-repo
          searchPaths: licensingservice,organizationservice
          username: raduAndrada
          password: warlord4me